### PR TITLE
Fix field name to match Dredd

### PR DESCRIPTION
**Pull request by IngmarStein**
Fixes a bug introduced in 0.3.0

### CODE REVIEW

**Comment by ddelnano** [comment]
@IngmarStein can you provide more context on what the issue is?  In the dredd docs it says that the key should be `schema`.

**Comment by IngmarStein** [comment]
Sorry, I could have been clearer but it seems you already found that dredd's documentation was out of sync and that the code actually uses `bodySchema` instead of `schema`.

**Comment by IngmarStein** [comment]
To add some detail: goodman 0.3.0 introduced all kinds of validation errors in our tests (mainly optional fields not being optional) and they were fixed by the change in this PR.

**Comment by ddelnano** [comment]
Yea basically I was trying to understand how bad this change was for users since the integration tests still passed.  I get this is the right change but I'd like to add additional testing that would would have failed the PR that broke things.  Do you have any of the failure output that can help determine what the appropriate tests would be?

**Comment by IngmarStein** [comment]
I got many errors similar to `At '/0/accounts' Missing required property: accounts`.
This example above relates to a data structure defined as follows:
```
## Access (object,fixed-type)

+ id:                    2                (number) - Unique id
+ name                                    (string) - Name of the access
+ enabled:               true             (boolean) - Flag if the access is enabled
+ is_pin_saved:          false            (boolean) - Flag indicating whether the PIN is saved with the access
+ accounts                                (array[Account],optional,fixed-type) - The accounts that belong to the access
+ provider_id:          `DE-BIN-10010010` (string) - Financial institution reference
```
I assume that the `optional` flag was lost in transmission due to the field name mismatch.

The expected response is simply defined as
```
+ Response 200 (application/json; charset=utf-8)

    + Attributes (array[Access], fixed-type)
```

**Comment by IngmarStein** [comment]
Maybe you can merge this PR and add a regression test in a separate one?

**Comment by ddelnano** [comment]
Yea I thought I would have time sooner rather than later but I'll have to add a test next chance I get.

**Pull request merged**
